---
title: "Selecting Portfolio"
output: html_document
---

```{r}
#Load Libraries
library('ggplot2')
library('quantmod')
library('GA')
library('GenSA')

```
Apply Genetic Algorithm to the Portfolio problem (part of SA.rmd). How does the performance of the GA compare to simulated annealing.
```{r}
#Feeding real-time stock data into the system

tickers <- c("BAC", "F", "GE", "AAPL", "WMT")
getSymbols(tickers, from = "2008-12-01", to = "2018-10-31")
P <- NULL
for(ticker in tickers) {
 tmp <- Cl(to.monthly(eval(parse(text = ticker))))
 P <- cbind(P, tmp)
}
colnames(P) <- tickers
R <- diff(log(P))
R <- R[-1,]
mu <- colMeans(R)
sigma <- cov(R)
library("PerformanceAnalytics")
pContribCVaR <- ES(weights = rep(0.2, 5), method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)$pct_contrib_ES
obj <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out <- tmp1 - 1e+3 * tmp2
 return(out)
}
obj1 <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out1 <- tmp1 + 1e+3 * tmp2
 return(out1)
}
```
```{r}
# Rastrigin function

Rastrigin <- function(x1, x2)
{
  20 + x1^2 + x2^2 - 10*(cos(2*pi*x1) + cos(2*pi*x2))
}

x1 <- x2 <- seq(-5.12, 5.12, by = 0.1)
f <- outer(x1, x2, Rastrigin)
persp3D(x1, x2, f, theta = 50, phi = 20, color.palette = spectral.colors)
```

```{r}
#Applying GA to assign weights for optimum portfolio using min objective
# Where x1 = BAC, x2 = F, x3 = GE, x4 = AAPL and x5 = WMT
# Solution is the weights assigned to each of the stocks for optimum portfolio
set.seed(1234)
fn.call <<- 0
gap <- ga(type = "real-valued",fitness=obj,lower=rep(0,5),upper=rep(1,5), popSize = 50,maxiter = 30, pcrossover = 0.75, pmutation = 0.1)
nsol <- gap@solution
nsol <- nsol / sum(nsol)
fn.call.gap <- fn.call
nsol
summary(gap)
plot(gap)
```
Applying GenSA to assign weights to the stocks for optimum portfolio using max objective
```{r}
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = obj1, lower = rep(0, 5), upper = rep(1, 5), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
cat("GenSA call functions", fn.call.GenSA, "times.\n")
wstar.GenSA <- out.GenSA$par
wstar.GenSA <- wstar.GenSA / sum(wstar.GenSA)
rbind(tickers, round(100 * wstar.GenSA, 2))
100 * (sum(wstar.GenSA * mu) - mean(mu))
wstar.GenSA
```

Comparing the weights as per both the algorithms
```{r}
b <- matrix(c(nsol, wstar.GenSA), nrow = 5, ncol = 2)
rownames(b) = c("BAC", "F", "GE", "AAPL", "WMT")
colnames(b) = c("GAPortfolio", "GenSAPortfolio")
b
```
Comparing the fitness function values
```{r}
l <- matrix(c(gap@fitnessValue, out.GenSA$value), nrow = 2)
rownames(l) = c('GA_Fitness_Value', 'GenSA_Fitness_value')
l
```